name: speech_to_text_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  word_cloud: ^1.0.3
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.2
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  intl: ^0.19.0
  fl_chart: ^0.66.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/keywords.json